# -- DB --
mariadb:
  image: mariadb:10.6
  rootPassword: "inanc123!"
  user: "wp_user"
  password: "wppass123!"
  dbName: "wp_"

# -- Wordpress --
wordpress: 
  image:
    repository: 10.0.2.15:30002/wordpress-project/my-wordpress
    tag: "0d14a1e660450c51d5e28b5f9c3d788bafdf1c08"
  service: 
    type: NodePort
    port: 80
    nodePort: 30081
  pvc: 
    enabled: true
    storage: 5Gi

# -- ingress --
ingress:
  enabled: true
  className: "traefik" 
  host: wordpress.local
  annotations: 
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: "web"
