# -- DB --
mariadb:
  image: mariadb:10.6
  rootPassword: "inanc123!"
  user: "wp_user"
  password: "wppass123!"
  dbName: "wp_"

# -- Wordpress --
wordpress: 
  image:
    repository: 10.0.2.15:30002/wordpress-project/my-wordpress
    tag: "2e549f9be0034b6a893cb866ec1f4a644b4acf19"
  service: 
    type: NodePort
    port: 80
    nodePort: 30081
  pvc: 
    enabled: true
    storage: 5Gi

# -- ingress --
ingress:
  enabled: true
  className: "traefik" 
  host: wordpress.local
  annotations: 
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: "web"
