name: WordPress CI/CD with Harbor and ArgoCD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: self-hosted 
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login to Harbor
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" | docker login ${{ secrets.HARBOR_URL }} -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin

      - name: Build and Push WordPress Image
        run: |
          # Commit SHA'yı tag olarak kullanıyoruz (Best Practice)
          IMAGE_TAG=${{ github.sha }}
          IMAGE_NAME=${{ secrets.HARBOR_URL }}/wordpress-project/wordpress
          
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest

      - name: Update Helm Chart Image Tag
        run: |
          # values.yaml içindeki imaj tag'ini yeni commit SHA ile güncelliyoruz
          sed -i 's/tag: .*/tag: "${{ github.sha }}"/' wordpress-project/values.yaml
          
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add wordpress-project/values.yaml
          git commit -m "chore: update image tag to ${{ github.sha }}"
          git push
