name: WordPress CI/CD with Harbor and ArgoCD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: self-hosted # ARC üzerindeki autoscale runner'larını kullanır
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Docker Login to Harbor
        # daemon.json düzenlemesi sayesinde artık buradan başarıyla geçecek
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" | docker login ${{ secrets.HARBOR_URL }} -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin

      - name: Build and Push WordPress Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          # HATA BURADAYDI: Parantezi iki adet "}}" ile kapattık
          IMAGE_NAME=${{ secrets.HARBOR_URL }}/wordpress-project/my-wordpress

          # Dockerfile wordpress-project içinde olduğu için context'i oraya veriyoruz
          docker build -t $IMAGE_NAME:$IMAGE_TAG ./wordpress-project
          docker push $IMAGE_NAME:$IMAGE_TAG
          
          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest

      - name: Update Helm Chart Image Tag
        run: |
          # values.yaml içindeki tag'i yeni commit SHA ile günceller
          sed -i 's/tag: .*/tag: "${{ github.sha }}"/' wordpress-project/values.yaml

          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add wordpress-project/values.yaml
          git commit -m "chore: update image tag to ${{ github.sha }} [skip ci]"
          git push
